version: "3.3"

services:

  postgres:
    container_name: PostgreSQL
    image: postgres:alpine
    restart: always
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auths
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  mailhog:
    container_name: Mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres: